version: '3.7'
services:
  db:
    container_name: db_goApiDb_tests
    image: mariadb:10.3.10-bionic
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_ROOT: ${DB_ROOT}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - 10101:3306
    volumes:
      - mariadb_goApiDb_tests:/var/lib/mysql

volumes:
  mariadb_goApiDb_tests: