name: Run Tests
run-name: Running Tests
on: pull_request


jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      maria-db:
        image: mariadb:10.3-bionic
        env:
          MYSQL_DATABASE: testing
        ports:
          - 10101:3306
    steps:
       - name: Run Tests
         run: |
          sudo apt-get install go
          go test ./tests
